services:
  app.cli:
    class: Symfony\Component\Console\Application
    autowire: true

  app.generator.command:
    class: Opdavies\GmailFilterBuilder\Console\Command\GenerateCommand
    autowire: true
    tags:
      - { name: ConsoleCommand }
